name: go-core
#监听动作
on: [push,pull_request]
jobs:
  build:
    name: go-core
    # 系统环境
    runs-on: ubuntu
    services:
      # 设置需要的服务
      mysql:
        image: mysql:5.7
        port:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: core
          MYSQL_ROOT_PASSWORD: root
          options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      redis:
        image: redis:6.0.1
        ports:
          - 6379:6379
      # 设置语言环境
      - name: golang
        uses: actions/setup-go@v2
        with:
        go-version: 1.15
      # 编译
      - name: Build



